### ISSUE TITLE
Version 1.5.0 hangs indefinitely 

### ISSUE THREAD

**Issue by beandrad** [orcasecurity/orca-cli#1]
The orca-cli image scan hangs for some images. This works with previous versions of the cli.

<img width="1051" alt="Screenshot 2022-10-07 at 14 52 26" src="https://user-images.githubusercontent.com/67916678/194560512-3e496eb1-e46a-4088-94b9-90b92b4b424e.png">

**Comment by Meandron** [comment]
We have the same issue having updated from 1.4.3 to 1.5.1

**Comment by Meandron** [comment]
Version 1.5.3 fixed is for us. However, would be great if someone would look into issues from your side.
