### ISSUE TITLE
pnpm lock file version 9 not supported?

### ISSUE THREAD

**Issue by hasanhakkaev** [orcasecurity/orca-cli#23]
Hi,

 we have encountered the issue with pnpm lock file version 9 that the orca cli is not recognizing the dependency versions and giving false positive results.
 
 
<img width="693" alt="image" src="https://github.com/orcasecurity/orca-cli/assets/14126525/acf5395f-b2b9-4f7a-9ef5-f5adaf8c1820">

<img width="1480" alt="image" src="https://github.com/orcasecurity/orca-cli/assets/14126525/58f577a9-e146-4cb8-9a54-3e1e37fc254c">

As seen here, it finds an older version of the dependency even though it's not in the lock file.
<img width="1484" alt="image" src="https://github.com/orcasecurity/orca-cli/assets/14126525/74d115c0-c2af-4c4c-804b-000b2d53d6cf">

**Comment by raghur-orca** [comment]
Hello @hasanhakkaev 
Thanks for reporting it. 
We do support pnpm-lock.yaml. 
Could you please create a support ticket with us with the your organisation and scan details for us to investigate this behaviour further?

**Comment by hasanhakkaev** [comment]
Hi @raghur-orca ,
i've created the ticket. Thanks for the quick help.

**Comment by raghur-orca** [comment]
Thank you @hasanhakkaev.
